### ISSUE TITLE
Not working on Redmine 4.1

### ISSUE THREAD

**Issue by sphereweb83** [paginagmbh/redmine_emojibutton#22]
When i try to run the `rake emoji RAILS_ENV=production` command i get the following error:

```
bitnami@redmineserver:/opt/bitnami/apps/redmine/htdocs$ rake emoji RAILS_ENV=production
rake aborted!
NoMethodError: undefined method `assets' for #<Rails::Application::Configuration:0x000056431d9624e8>
Did you mean?  asset_host
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_emojibutton/init.rb:16:in `block in <top (required)>'
/opt/bitnami/apps/redmine/htdocs/config/environment.rb:16:in `<top (required)>'
/opt/bitnami/apps/redmine/htdocs/plugins/recurring_tasks/lib/tasks/recurring_tasks.rake:7:in `<top (required)>'
/opt/bitnami/apps/redmine/htdocs/lib/tasks/redmine.rake:202:in `block in <top (required)>'
/opt/bitnami/apps/redmine/htdocs/lib/tasks/redmine.rake:202:in `each'
/opt/bitnami/apps/redmine/htdocs/lib/tasks/redmine.rake:202:in `<top (required)>'
/opt/bitnami/apps/redmine/htdocs/Rakefile:7:in `<top (required)>'
(See full trace by running task with --trace)
```

Please help?

**Comment by tofi86** [comment]
Thanks for the report. The plugin is not tested with 4.1 yet. I will try to have a look at the weekend.

**Comment by jr180180** [comment]
@sphereweb83 - I've added PR #24 for this but you can accomplish what this PR does manually.

With Redmine v4.1
1. Open your `config/application.rb` file and uncomment the "sprockets/railtie" require line.
2. Create a `app/assets/config/manifest.js` file for sprockets

You can do that manually and place `{}` in the file or run the following command via your terminal:

```
mkdir -p app/assets/config && echo '{}' > app/assets/config/manifest.js
```

**Comment by adrianobr** [comment]
+1

**Comment by tofi86** [comment]
As described here (https://www.redmine.org/issues/32852#note-2) and in other Redmine sources, it's discouraged to alter `config/application.rb`. I think we have to find another solution...

**Comment by tofi86** [comment]
By the way: The branch `gemoji-4.0-native-emojis-no-images` works fine in 4.1 because it does not rely on any assets. The branch is still "work-in-progress", though I use it in production for quite a while now. This is the note from `README.md` about it:

> **PLEASE NOTE:** The `master` branch uses images to display emojis and therefore has a consistent display across all operating systems. The downside, however, is that there is no support for *latest* Unicode 10+ emojis – and will never be! If you want to use the latest Unicode emojis displayed in the operating systems default emoji font please use the pre-release version v0.6.0 from the `gemoji-4.0-native-emojis-no-images` branch. It uses the `gemoji` gem and displays emojis as native Unicode emojis.

**Comment by hermannkm** [comment]
Not working in 4.2, 

```
rake aborted!
NoMethodError: undefined method `assets' for #<Rails::Application::Configuration:0x00005646a66e64a8>
Did you mean?  asset_host
/home/redmine/.rvm/gems/ruby-2.7.2/gems/railties-5.2.6/lib/rails/railtie/configuration.rb:97:in `method_missing'
```

although switched to 

```
$ git branch -a
  master
* remotes/origin/gemoji-4.0-native-emojis-no-images
  remotes/origin/HEAD -> origin/master
  remotes/origin/gemoji-4.0-native-emojis-no-images
  remotes/origin/master
  remotes/origin/test/gemoji-3.3-with-emojionearea-picker
  remotes/origin/test/gemojione
```
