### PR TITLE
Add compatibility for Redmine v4.1

### LINKED ISSUE #22: Not working on Redmine 4.1
When i try to run the `rake emoji RAILS_ENV=production` command i get the following error:

```
bitnami@redmineserver:/opt/bitnami/apps/redmine/htdocs$ rake emoji RAILS_ENV=production
rake aborted!
NoMethodError: undefined method `assets' for #<Rails::Application::Configuration:0x000056431d9624e8>
Did you mean?  asset_host
/opt/bitnami/apps/redmine/htdocs/plugins/redmine_emojibutton/init.rb:16:in `block in <top (required)>'
/opt/bitnami/apps/redmine/htdocs/config/environment.rb:16:in `<top (required)>'
/opt/bitnami/apps/redmine/htdocs/plugins/recurring_tasks/lib/tasks/recurring_tasks.rake:7:in `<top (required)>'
/opt/bitnami/apps/redmine/htdocs/lib/tasks/redmine.rake:202:in `block in <top (required)>'
/opt/bitnami/apps/redmine/htdocs/lib/tasks/redmine.rake:202:in `each'
/opt/bitnami/apps/redmine/htdocs/lib/tasks/redmine.rake:202:in `<top (required)>'
/opt/bitnami/apps/redmine/htdocs/Rakefile:7:in `<top (required)>'
(See full trace by running task with --trace)
```

Please help?

### PR DESCRIPTION
**Pull request by jr180180**
Fixes #22

Not sure this is the best course of action but doing what that rake task does for you with a Redmine v4.1 installation gets it working.

### CODE REVIEW

**Comment by adrianobr** [comment]
+1

**Comment by tofi86** [comment]
As described here (https://www.redmine.org/issues/32852#note-2) and in other Redmine sources, it's discouraged to alter `config/application.rb`. I think we have to find another solution...
